export const productCardData = [
  {
    title: `Wooden water bottle`,
    oldPrice: `रु 3000`,
    newPrice: `रु 2000.00`,
    price: 2000,
    category: "Bottles",
    material: "Natural Wood",
    rating: 4.6,
    desc1: `Natural Wood - Small`,
    desc2: `Crafted from premium, responsibly sourced wood, this water 
    bottle is designed for those who value sustainability 
    without compromising style. The smooth wooden exterior 
    feels natural to the touch, while the leak-proof aluminum 
    cap ensures your beverages stay secure. Ideal for daily use
    , outdoor adventures, or the office, this bottle keeps your 
    drinks fresh and adds a touch of eco-conscious elegance to 
    your routine. Reusable, durable, and beautifully designed,
     a perfect companion for a greener lifestyle.`,
    images: [
      `/images/wooden-bottle2.jpg`,
      `/images/wood-bottle.png`,
      `/images/Water-Bottle-Wood.jpg`,
    ],
  },
  {
    title: `Beeswax Food Wraps`,
    oldPrice: `रु 1500`,
    newPrice: `रु 900.00`,
    price: 900,
    category: "Kitchen",
    material: "Beeswax",
    rating: 4.2,
    desc1: `Reusable food wrap`,
    desc2: `Ditch single-use plastic with these beeswax food wraps. Made from organic cotton coated with natural beeswax, they keep fruits, vegetables, and leftovers fresh while being fully reusable and biodegradable. Flexible, durable, and easy to clean, they’re a sustainable addition to any kitchen.`,
    images: [
      `/images/beeswax-food-wrap.jpg`,
      `/images/Beeswax_Wrap_quickView.jpg`,
      `/images/Beeswax_Wrap_3.jpg`,
    ],
  },
  {
    title: `Cloth Bag`,
    oldPrice: `रु 1200`,
    newPrice: `रु 800.00`,
    price: 800,
    category: "Accessories",
    material: "Fabric",
    rating: 4.0,
    desc1: `Reusable tote bag`,
    desc2: `Say goodbye to plastic bags with this eco-friendly cloth tote. Made from high-quality, sturdy fabric, it’s perfect for groceries, shopping, or daily errands. Lightweight yet spacious, washable, and reusable, a simple way to make a sustainable choice every day.`,
    images: [
      `/images/tote-bag.jpg`,
      `/images/tote-bag-quic-view.jpg`,
      `/images/cloth-bag-3.jpg`,
    ],
  },
  {
    title: `Bamboo Straws`,
    oldPrice: `रु 1700`,
    newPrice: `रु 1200.00`,
    price: 1200,
    category: "Kitchen",
    material: "Bamboo",
    rating: 4.4,
    desc1: `Set of bamboo straws`,
    desc2: `Replace plastic straws with these natural bamboo alternatives. Smooth, lightweight, and durable, they’re easy to clean and reusable. Perfect for cold and hot beverages alike, these bamboo straws make every sip eco-conscious and stylish.`,
    images: [
      `/images/bamboo-straws.jpg`,
      `/images/bamboo_straws_quick-view.jpg`,
      `/images/Bamboo-Straws-3.jpg`,
    ],
  },
  {
    title: `Wooden Toothbrush`,
    oldPrice: `रु 1999`,
    newPrice: `रु 1750`,
    price: 1750,
    category: "Hygiene",
    material: "Natural Wood",
    rating: 4.1,
    desc1: `Biodegradable wooden toothbrush`,
    desc2: `Keep your oral hygiene eco-friendly with this wooden toothbrush. The biodegradable handle is crafted from responsibly sourced wood, and soft bristles provide gentle yet effective cleaning. Reduce plastic waste while maintaining your daily dental routine.`,
    images: [
      `/images/toothbrush.jpg`,
      `/images/toothbrush-quick-view.webp`,
      `/images/toothbrush3.jpg`,
    ],
  },
  {
    title: `Disposable Trash Bags`,
    oldPrice: `रु 1000`,
    newPrice: `रु 800.00`,
    price: 800,
    category: "Home",
    material: "Biodegradable",
    rating: 3.9,
    desc1: `Compostable trash bags`,
    desc2: `These disposable trash bags are fully compostable, providing a responsible solution for household waste. Strong, durable, and leak-resistant, they break down naturally after disposal, helping you maintain a clean and eco-conscious home.`,
    images: [
      `/images/Disposable-trash-bags.jpg`,
      `/images/disposable-trash-bags-quick-view.png`,
      `/images/disposable-trash-bags-quick-view2.png`,
    ],
  },
  {
    title: `Wooden Comb`,
    oldPrice: `रु 1000`,
    newPrice: `रु 600.00`,
    price: 600,
    category: "Hygiene",
    material: "Natural Wood",
    rating: 4.3,
    desc1: `Neem wooden comb`,
    desc2: `Pamper your hair with this smooth wooden comb. Crafted from quality wood, it reduces static, gently detangles, and supports healthy hair. A sustainable alternative to plastic combs, perfect for daily grooming.`,
    images: [
      `/images/neem-wooden-comb.jpg`,
      `/images/comb2.jpg`,
      `/images/comb3.jpg`,
    ],
  },
  {
    title: `Laundry Sheets`,
    oldPrice: `रु 1500`,
    newPrice: `रु 650.00`,
    price: 650,
    category: "Laundry",
    material: "Biodegradable",
    rating: 4.5,
    desc1: `Concentrated laundry sheets`,
    desc2: `Simplify laundry while reducing plastic waste with these plant-based laundry sheets. Compact, lightweight, and pre-measured, they dissolve completely in water and leave clothes fresh and clean without harsh chemicals. Perfect for sustainable living at home or on the go.`,
    images: [
      `/images/laundry-sheets.jpg`,
      `/images/laundry-sheets-quick-view.jpg`,
      `/images/laundry-sheets-3.jpg`,
    ],
  },
  {
    title: `Natural sponge`,
    oldPrice: `रु 800`,
    newPrice: `रु 450.00`,
    price: 450,
    category: "Kitchen",
    material: "Wood",
    rating: 4.0,
    desc1: `Biodegradable kitchen sponge`,
    desc2: `This natural kitchen sponge is made from plant-based materials and is fully biodegradable. Tough on grease yet gentle on surfaces, it’s perfect for everyday dishwashing while reducing plastic waste in your kitchen.`,
    images: [
      `/images/sponge.jpg`,
      `/images/sponge1.jpg`,
      `/images/sponge2.jpg`,
    ],
  },
  {
    title: `Eco-friendly Doormat`,
    oldPrice: `RS 3000`,
    newPrice: `2500`,
    price: 2500,
    category: "Bath",
    material: "Wood",
    rating: 3.8,
    desc1: `Medium eco comb`,
    desc2: `Made from natural, durable fibers, this eco-friendly doormat effectively traps dirt and moisture while adding a rustic, sustainable touch to your home entrance. Long-lasting, biodegradable, and perfect for indoor or outdoor use.`,
    images: [
      `/images/doormat.jpg`,
      `/images/doormat2.jpg`,
      `/images/doormat3.jpg`,
    ],
  },
];
